x = int(input())
y = int(input())
hx = (34 - x)
hy = (220- y)
dh = (hx**2 + hy**2)**(1/2)
kx = (0 - x)
ky = (0 - y)
dk = (kx**2 + ky**2)**(1/2)
sx = (140 - x)
sy = (456 - y)
ds = (sx**2 + sy**2)**(1/2)
print(f'Distancia para Hogsmeade: {dh:.2f}')
print(f'Distancia para Kakariko: {dk:.2f}')
print(f'Distancia para Solitude: {ds:.2f}')
